In [1]:
using DelimitedFiles, Statistics, Random

In [2]:
filePath = download("https://raw.githubusercontent.com/ilkerkesen/ufldl-tutorial/master/ex1/housing.data")

"C:\\Users\\acer\\AppData\\Local\\Temp\\jl_C88C.tmp"

In [3]:
data = readdlm(filePath)

506×14 Array{Float64,2}:
 0.00632  18.0   2.31  0.0  0.538  6.575  …  296.0  15.3  396.9    4.98  24.0
 0.02731   0.0   7.07  0.0  0.469  6.421     242.0  17.8  396.9    9.14  21.6
 0.02729   0.0   7.07  0.0  0.469  7.185     242.0  17.8  392.83   4.03  34.7
 0.03237   0.0   2.18  0.0  0.458  6.998     222.0  18.7  394.63   2.94  33.4
 0.06905   0.0   2.18  0.0  0.458  7.147     222.0  18.7  396.9    5.33  36.2
 0.02985   0.0   2.18  0.0  0.458  6.43   …  222.0  18.7  394.12   5.21  28.7
 0.08829  12.5   7.87  0.0  0.524  6.012     311.0  15.2  395.6   12.43  22.9
 0.14455  12.5   7.87  0.0  0.524  6.172     311.0  15.2  396.9   19.15  27.1
 0.21124  12.5   7.87  0.0  0.524  5.631     311.0  15.2  386.63  29.93  16.5
 0.17004  12.5   7.87  0.0  0.524  6.004     311.0  15.2  386.71  17.1   18.9
 0.22489  12.5   7.87  0.0  0.524  6.377  …  311.0  15.2  392.52  20.45  15.0
 0.11747  12.5   7.87  0.0  0.524  6.009     311.0  15.2  396.9   13.27  18.9
 0.09378  12.5   7.87  0.0  0.524  5.88

In [4]:
y_array = data[:,end] ## size= 506 x 1
y_array = reshape(y_array,(1,506)) ## size= 1 x 506

matrix = fill(0.0,(13,506))
for i in 1:13, j in 1:506
    matrix[i,j] = data[j,i]
end

In [5]:
mean_array = mean(matrix,dims=2)  
std_array = std(matrix;dims=2) 
for i in 1:13, j in 1:506
    matrix[i,j] = (matrix[i,j] - mean_array[i])/(std_array[i])
end
matrix

13×506 Array{Float64,2}:
 -0.419367  -0.416927  -0.416929  …  -0.413038  -0.407361  -0.41459 
  0.284548  -0.48724   -0.48724      -0.48724   -0.48724   -0.48724 
 -1.28664   -0.592794  -0.592794      0.115624   0.115624   0.115624
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329
 -0.144075  -0.73953   -0.73953       0.157968   0.157968   0.157968
  0.413263   0.194082   1.28145   …   0.983986   0.724955  -0.362408
 -0.119895   0.366803  -0.265549      0.796661   0.736268   0.434302
  0.140075   0.556609   0.556609     -0.772919  -0.667776  -0.61264 
 -0.981871  -0.867024  -0.867024     -0.981871  -0.981871  -0.981871
 -0.665949  -0.986353  -0.986353     -0.802418  -0.802418  -0.802418
 -1.45756   -0.302794  -0.302794  …   1.1753     1.1753     1.1753  
  0.440616   0.440616   0.396035      0.440616   0.402826   0.440616
 -1.0745    -0.491953  -1.20753      -0.982076  -0.864446  -0.668397

In [6]:
xtrn = fill(0.0,(13,400))
xtest = fill(0.0,(13,106))

ytrn = fill(0.0,(1,400))
ytest = fill(0.0,(1,106))

Random.seed!(1) 
randomValues = randperm(506) ##random generate value

xtrn = matrix[:,randomValues[1:400]]     ## xtrn filled
ytrn = y_array[:,randomValues[1:400]]    ## ytrn fiiled
xtest = matrix[:,randomValues[401:end]]  ## xtest filled
ytest = y_array[:,randomValues[401:end]] ## ytest filled

1×106 Array{Float64,2}:
 20.3  27.5  22.0  30.7  19.4  24.5  …  24.8  42.3  16.3  19.1  20.3  29.8

In [7]:
w = randn(1,13) * (0.1) #define weight

1×13 Array{Float64,2}:
 0.0426637  0.0378471  -0.169487  …  -0.0208622  -0.066244  -0.0257344

In [8]:
ypred_train = w * xtrn

1×400 Array{Float64,2}:
 0.227025  -0.0623266  -0.0604358  …  0.207288  0.0592333  -0.0221864

In [9]:
total_train_loss = fill(0.0,(1,1))
train_loss = (ytrn - ypred_train).^2
for i in 1:400
    total_train_loss[1] = total_train_loss[1] + train_loss[i]
end
total_train_loss = (1/(2*400))*total_train_loss

1×1 Array{Float64,2}:
 297.3036503276774

In [10]:
ypred_test = w * xtest
total_test_loss = fill(0.0,(1,1))
test_loss = (ytest - ypred_test).^2
for i in 1:106
    total_test_loss[1] = total_test_loss[1] + test_loss[i]
end
total_test_loss = (1/(2*106))*total_test_loss

1×1 Array{Float64,2}:
 299.0172855668773

In [11]:
result = fill(0.0,(1,1))
yError = ytrn - ypred_train
ySqrt  = sqrt(total_train_loss) 
for i in 1:400
    result[1] = yError[i] < ySqrt[1]  ? result[1] + 1 : result[1]
end
result

1×1 Array{Float64,2}:
 108.0